version: "3.9"
services:
  invhub-django:
    container_name: "invhub-django"
    image: "invhub-django:${APP_VER}"
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - invhub
networks:
  invhub:
    external: true