# Generated by Django 4.2.5 on 2023-09-11 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventori_crud", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventori_crud.inventory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventori_crud.product",
                    ),
                ),
            ],
            options={"db_table": "product_component",},
        ),
    ]
